### ISSUE TITLE
三个问题

### ISSUE THREAD

**Issue by Lawrence1233** [wuyuhangxyz/XesScript#2]
第46行
    def parseWorkURL(self, url: str) -> dict:
        import requests
什么都没写

第487行
    def __init__(self) -> None:
        pass
        url = parse.urlparse(url)
        parad = parse.parse_qs(url.query)
        return parad
此处不应该返回内容

683行
contact = self.getUserContact()
缺少page值

**Comment by wuyuhangxyz** [comment]
???怎么回事？不好意思我好像上传错文件了，我上传的是我用来测试的文件

**Comment by wuyuhangxyz** [comment]
真的离谱，这不是我的锅，这是github WebIDE的锅，怎么回事，我把代码粘贴过来的时候出了很大的问题，另外是不是没有constant这个库
