### ISSUE TITLE
定义了两次类

### ISSUE THREAD

**Issue by Lawrence1233** [wuyuhangxyz/XesScript#3]
第8行的xeswork类
第57行再次定义了一次

第353行的XesOneself类
第747行再次定义了一次

第420行的XesIndex类
第753行再次定义了一次

第448行的XesExplore类
第759行再次定义了一次

第482行的XesBehavior类
第765行再次定义了一次

写代码要好好检查啊骚年

**Comment by wuyuhangxyz** [comment]
这真不是我的问题，是我在github里面粘贴代码的时候出的问题，github的webide怎么不能多行选中啊啊啊，我就说看着issue怎么我一个400多行的库有了700多行。。。
